services:
  pgdatabase:
    image: postgres:13
    container_name: pgdatabase
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=personal_dashboard
    volumes:
      - "/home/neil/Personal-Dashboard/postgres_data:/var/lib/postgresql/data:rw"      
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - /home/neil/Personal-Dashboard/data_pgadmin:/var/lib/pgadmin      
    ports:
      - "8080:80"
  pythonapp:
    container_name: pythonapp
    build: ./
    command: python3 ./src/pipeline/run.py
    depends_on:
      pgdatabase:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=pgdatabase