services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=personal_dashboard
    volumes:
      - "/home/neil/Personal-Dashboard/postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - /home/neil/Personal-Dashboard/data_pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
      